name: ✨ Đề xuất tính năng
description: Đề xuất tính năng mới
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Mô tả tính năng
      placeholder: Bạn muốn tính năng gì?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Lý do
      placeholder: Tại sao tính năng này hữu ích?

  - type: dropdown
    id: platform
    attributes:
      label: Nền tảng
      options:
        - Tất cả
        - macOS
        - Windows
